import type { Metadata } from "next";
import "./globals.css";
import localFont from 'next/font/local';
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const myCustomFont = localFont({
  src: '../../public/fonts/font.ttf', 
  variable: '--font-my-custom-font', 
  display: 'swap', 
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={myCustomFont.className}>
      <body className="flex flex-col min-h-screen">
        {/* Navbar at top (not fixed anymore) */}
        <Navbar />

        {/* Main content grows to fill remaining space */}
        <main className="flex-grow px-4">
          {children}
        </main>

        {/* Footer will stick to bottom if content is short */}
        <Footer className=""/>
      </body>
    </html>
  );
}
